### ISSUE TITLE
The links in alerts are not clickable

### ISSUE THREAD

**Issue by tumido** [operate-first/SRE#121]
The links used in these alerts are not clickable, could we change that?

_Originally posted by @goern in https://github.com/operate-first/SRE/issues/119#issuecomment-795477922_

/kind bug

**Comment by goern** [comment]
;)

/sig user-experience

**Comment by 4n4nd** [comment]
@hemajv do you want to look into this issue?

**Comment by hemajv** [comment]
Since the links are pointing to the services within the k8s cluster, they do not work outside the cluster. These service names are configured in prometheus and known to the alertmanager and we would need to use the `--web.external-url` flag to specify our Prometheus/Alertmanager URLs to make sure the clickable links are plumbed through.

Reference:
1. [alertmanger flag](https://github.com/prometheus/alertmanager/blob/0fef08028bbc3a8b02dffd8ce26b60b4be710bb7/cmd/alertmanager/main.go#L191)
2. [prometheus flag](https://github.com/prometheus/prometheus/blob/ad5ed416ba635834370bfa06139258b31f8c33f9/cmd/prometheus/main.go#L197)
