### ISSUE TITLE
Personal private keys in sops configuration?

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#122]
I'd like to be able to add pgp keys for individuals to the sops configuration in e.g. the apps repository, to permit people to view encrypted documents without sharing out the argocd private key everywhere. E.g., I wanted to share the changes in https://github.com/operate-first/apps/pull/340 with @ipolonsk, but because it's encrypted it's not terribly useful as an example if one can't decrypt the content.

Have we thought about this at all?

**Comment by tumido** [comment]
Yes, @larsks you can use multiple keys to encrypt a single resource with sops.

1. You either need to add it to the `.sops.yaml` rule. For example here we use multiple GPG keys in AIOps org:
https://github.com/aicoe-aiops/project-template/blob/master/manifests/.sops.yaml 


2. Or just encrypt it directly via sops command (bypassing the config file) like this:

```
sops -e --encrypted-regex="^(users|data|stringData)$" --pgp="0508677DD04952D06A943D5B4DC4116D360E3276, NEXT_KEY, NEXT_KEY" resource.yaml > resource.enc.yaml
```

I'd say the option 2 is preferred. And since the configuration is stored in the encrypted file, any update on the resource will automatically use all the keys as well.

**Comment by HumairAK** [comment]
We've briefly talked about this in other parts of the repo. For example, we advertise that -- should a team want the ability to update their team's ocp group, they can provide their gpg and we can include it as one of the keys used for encryption. 

A quick solution would be to just re-encrypt using both keys, argocd's and @ipolonsk 's. 

What we could to, do be more organized about this is -- we can include an owners file for different sections of the apps repo, and have each owner provide their gpg key to encrypt all the secrets within those subdirectories. 

We wanted to add these owner files anyway for separating out approver permissions. We could just compliment them with an accompanying sops.yaml file with their keys as well, alongside the argocd gpg key.

**Comment by larsks** [comment]
> I'd say the option 2 is preferred. And since the configuration is stored in the encrypted file, any update on the resource will automatically use all the keys as well.

I think the first option would be preferable in most cases. That we don't need to remember, when creating new content, to encrypt it to additional people. I'd rather see things consistent if not across the entire repository than at least within specific hierarchies, as suggested by @HumairAK .

**Comment by tumido** [comment]
> I think the first option would be preferable in most cases

Unfortunately the `.sops.yaml` rules are very tricky to get right and because first rule that hits is used - which is very tricky with path regexes and encrypted data regexes. It also depends from which folder you're executing the `sops` command if there are multiple `.sops.yaml`s the resolution is dependent on the execution context (`cwd` vs directory of the encrypted resource, etc). Therefore we kinda settled on the second option after unsuccessfully fiddling with the first, because we couldn't get reliable results.

Also, once a resource is encrypted, no `.sops.yaml` rule changes apply to it anymore - only the metadata in the encrypted file itself matters. So the `.sops.yaml` is here mostly to provide reliable defaults, but it should not be trusted...

**Comment by larsks** [comment]
> So the .sops.yaml is here mostly to provide reliable defaults...

Having reliable defaults seems like a good idea. In particular, if we're only relying on `.sops.yaml` to set the recipients and never directly encrypting via the `--pgp` option, that seems like a reasonable solution. We'd have to occasionally re-key files when `sops.yaml` is modified, of course, but skew between the sops configuration and the keys configured in an encrypted file is probably something we could audit.
