### ISSUE TITLE
MOC Infra cluster console is down

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#125]

**Comment by HumairAK** [comment]
from @larsks : 

```
The API seems up, and oc get nodes shows everything up and running.

But I see that the console is down...

The apps vip address was hosted by a node that is not part of the cluster. There are two worker nodes left over from the previous install that are still running, but it looks like they may somehow be participating in things.

```

**Comment by HumairAK** [comment]
Console looks like it's back up.

**Comment by HumairAK** [comment]
Down again

**Comment by larsks** [comment]
While investigating https://github.com/operate-first/apps/issues/285 I noticed that the apps VIP for the moc-infra cluster was held by a host that was *not* a cluster member. There were two worker nodes left over from the previous `cnv2.massopen.cloud` cluster that seemed to still be participating in the `moc-infra` cluster, despite not being cluster nodes.

Requests from pods in  `zero.massopen.cloud` to `*.apps.moc-infra.massopen.cloud` were getting handled by an ingress router on one of these rogue worker nodes, rather than by the `moc-infra` ingress router.

It looks like some traffic was routing successfully through these rogue nodes, because shutting them down rendered the moc-infra console ui unavailable (although it resolved the original issue in operate-first/apps#285).

**Comment by larsks** [comment]
I have restarted the console pods on the moc-infra cluster, and the console ui now seems to be reliably available. Looking for confirmation from @HumairAK at least before closing.

**Comment by HumairAK** [comment]
LGTM thanks @larsks !
