### ISSUE TITLE
Identify On-call process for common issues, procedures, prs.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#217]

**Comment by durandom** [comment]
Think of it as first-level support, the person should

* monitor all newly created issues in the following repos: ...
* triage the issue: label and reply
* self-assign if the issue is "trivial", e.g. steps are documented in RUNBOOK
* route/assign to the appropriate person

links: https://sre.google/sre-book/being-on-call/

**Comment by HumairAK** [comment]
@4n4nd @tumido  @hemajv  @anishasthana  

Looking for thoughts on how to select an on-call person on a weekly bases.

**Comment by anishasthana** [comment]
Internally we just have a scheduled rotation on PagerDuty. If people have PTO/busy weeks, they can trade with other people. So far it's worked pretty well for us.

**Comment by HumairAK** [comment]
Pagerduty is overkill for us right now. I'm just looking for a simple way to pick a person and have it maybe displayed/notified somewhere.

**Comment by anishasthana** [comment]
Well, Pagerduty is just an implementation detail right?  Prior to using pagerduty, we just had a jenkins workflow go through a list of names in order. You could probably do the same with an Argo Workflow

**Comment by HumairAK** [comment]
We will have @tumido's bot handle the on-call assignments. https://github.com/tumido/slack-first

**Comment by HumairAK** [comment]
done, thanks @tumido for the awesome bot!! 
https://github.com/operate-first/apps/pull/484
