### ISSUE TITLE
block access to all logs/metrics

### ISSUE THREAD

**Issue by durandom** [operate-first/SRE#270]
Due to some legal concerns, we have to block access to anything that could expose PII.

- [x] loki
- [x] elastic (CLO)
- [x] kibana (CLO)
- [x] grafana
- [x] prometheus
- [x] thanos
- [x] jupyterhub pod access (? added by @tumido)

Blocking can be as easy as shutting it completely off to restricting access to a usergroup.
Let's brainstorm on solutions that are easy to implement and that provide value in the long-term.

**Comment by durandom** [comment]
@hpdempsey @billburnseh do we want to limit access to authenticated users or an even smaller group?

**Comment by 4n4nd** [comment]
Grafana Proxy Added: https://grafana-route-opf-monitoring.apps.zero.massopen.cloud/

**Comment by tumido** [comment]
CLO is restricted. User can login using their credentials - that grants them access to their applications only. If they want to access infra logs, they has to be added into [`cluster-logs-readers`](https://github.com/operate-first/apps/blob/master/cluster-scope/base/clusterrolebindings/cluster-logs-readers/clusterrolebinding.yaml).

**Comment by tumido** [comment]
Maybe we need to restrict the pod list/get access from all authenticated users as well?

Ref: https://github.com/operate-first/apps/blob/master/cluster-scope/components/project-logs-reader/rolebinding.yaml

**Comment by HumairAK** [comment]
Can we define " block access ", who should we be blocking from access?

The pr's linked above basically make it so that only operate-first admins can see prometheus/grafana, wouldn't this be antithetical to what we are trying to accomplish? I.e. allowing people other than the operators to see how these services are operated, and try them out? 

We have some docs about how to onboard people's services to our monitoring, can we give these folks access?

**Comment by 4n4nd** [comment]
For Loki and Thanos, since Observatorium Operator does not allow us to add separate containers to the existing deployments, we will need to create a separate deployment for the oauth-proxies. For this, I will create a single "Observatorium-proxy" deployment that will have multiple proxy containers for Loki and Thanos.
@tumido @HumairAK do you folks have any suggestions for this solution?

**Comment by 4n4nd** [comment]
Proxies added to all the metric/log components :+1:

**Comment by HumairAK** [comment]
Awesome thanks @4n4nd then this ticket is complete, please re-open if there is more.
