### ISSUE TITLE
CLO's ES operator being oomkilled 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#271]
The pod found [here](https://console-openshift-console.apps.zero.massopen.cloud/k8s/ns/openshift-operators-redhat/pods) is being oomkilled upon starting. This is manged by the ES operator which in turn is managed by the CLO.

**Comment by tumido** [comment]
So.. I've briefly looked into this. I think we should try uninstalling the operator and installing it again.

I've noticed that the ES operator `stable` channel is reporting different CSV than we have installed now:
![image](https://user-images.githubusercontent.com/7453394/117293114-4d848500-ae71-11eb-9645-976f1c77268b.png)

![image](https://user-images.githubusercontent.com/7453394/117293127-55dcc000-ae71-11eb-8ff0-e8bfb6db1c99.png)


Maybe it's stuck on the `5.0.0-65` version and this problem is already fixed in `5.0.2-18`.

Should I try it, WDYT @HumairAK ?

**Comment by HumairAK** [comment]
yeah let's try it

**Comment by tumido** [comment]
Uninstalling and syncing from ArgoCD made the operator to upgrade to `elasticsearch-operator.5.0.3-6`. Operator pod is running now. Let's see what's gonna happen now.

**Comment by tumido** [comment]
Seems the pod resource limits were completely removed with the upgrade - so I don't see this issue coming back. Closing. Feel free to reopen if this starts occurring again.
