### ISSUE TITLE
Do we need better alerting channels?

### ISSUE THREAD

**Issue by larsks** [operate-first/SRE#319]
We currently deliver all alerts into the [alerts](https://github.com/operate-first/alerts/) repository. We have #274 which addresses the source side of things (cleaning up which alerts get delivered), but we also need to think about the sink side of things -- where do we deliver alerts?

Even if we're able to substantially reduce the volume of the alert stream, is the `alerts` repository the best destination for alerts? Should we have some alerts feeding into e.g. a slack channel?

I don't have a strong opinion, but I'd like to make sure that in the future we avoid situations like #312, where we had something like 24 hours notice about the storage problems but we didn't notice the alert.

**Comment by HumairAK** [comment]
I think one could consider the way we handle alerts currently as an abuse of github issues. 

A quick google search led me to: https://github.com/target/goalert

**Comment by tumido** [comment]
I think there are 2 aspects to this that we need to consider and support:

1. Storing and surfacing alerts in an open-source way:
  - Provides an open way to correlate alerts and incidents and resolutions (via GH Issues/PRs)
  - Provide an easier onboarding to SRE - future SREs can gain insights into alerts right away
  - This is important for research projects like deCorus
2. Provide alerts and notifications to on-call response team
  - Totally different usecase
  - Required for timely resolution or preemptive mitigation

We're currently at the stage where we have the no. 1 covered. With https://github.com/operate-first/SRE/issues/274 we know now how to narrow the scope down to meaningful alerts. This is all on track towards no. 2.

It is important to mention that GitHub Issues for alerts is currently our only platform for long term alert storage that is public facing, open and queryable and can be easily correlated with discussions over incidents and tied to resolutions. We should not be moving away from this, unless we provide an alternative.

We can define multiple receivers for the same alerts for SRE convenience. That should cover no. 2. Slack alerting is a natural choice I think and it should be fairly straightforward to set up. I also think it's worth mentioning that we **should not** just replace GH receiver by a Slack one, because in the end we totally need to support no. 1.

**Comment by tumido** [comment]
Also another option that is very easy to set up and requires ~zero configuration on our side - we don't have to send alerts to Slack directly from OCPs, instead we can use GitHub Slack app and "just" subscribe to the GitHub issues via that Slack application.

**Comment by HumairAK** [comment]
I'd also like folks to ask themselves, what does the ideal solution look like? 

1. use our existing system and improve on it? i.e. implement improvements to gh alerts. If we drive our efforts here, we can set up slack integration as mentioned above. Additional tooling to ping the _right_ people for the appropriate alerts (presumably defined in some config file). 
2. look for alternative alerting tools (like the one I linked above)
3. A combinationg of 1) and 2)

**Comment by HumairAK** [comment]
I think a nice end goal is to be able to divert alerts to the right people, so we can delegate some of the work. Like JH alerts would alert ODH dev team. Network related issues with the cluster would alert infra/ops folks, etc. etc. 

With some of this stuff being cross-organizational, and not everyone being on our slack, I'm leaning towards improving our github alerts, and better parsing of of the content body of an alert to ping the right people.

**Comment by 4n4nd** [comment]
> Should we have some alerts feeding into e.g. a slack channel?

I think this is a good idea since we use slack for a lot of our communication. This way we could also use @tumido 's bot to tag the person who is on-call at the time of the alert.

**Comment by anishasthana** [comment]
Slack alerts will definitely result in alert fatigue. I'd highly recommend having a very restricted set of alerts going to slack.

**Comment by larsks** [comment]
I agree with @anishasthana re: alert fatigue, but for a couple of the problems we've had recently (storage filling up, certificate expiring) I wish the associated alert had been more "active" (like a slack notification, for example). In both cases, there was an imminent, cluster wide problem, and if we had known about it ahead of time we could have prevented the problem.

I think continuing to use the existing github-based mechanism is fine, provided we can create issues with more metadata (such as priority) than we do right now. This makes gives us more options for selecting which ones might trigger some other alert channel.

**Comment by tumido** [comment]
Related: https://operatefirst.slack.com/archives/C01RF4SPNDD/p1624439454065200

**Comment by HumairAK** [comment]
>  provided we can create issues with more metadata (such as priority) than we do right now. 

Following up from discussions in chat/calls. The answer to this is no, we can't. 

The [alertmanager-github-receiver](https://github.com/m-lab/alertmanager-github-receiver) doesn't offer this functionality. It was proposed that we simply contribute this feature upstream (and of they don't want it, we maintain our own fork). 

I'll create some issues regading this in a new epic.
