### ISSUE TITLE
Add monitoring for scrape duration

### ISSUE THREAD

**Issue by HumairAK** [operate-first/SRE#80]
As we add more metrics, the scrape durations for cluster-monitor-federation goes up. We don't want this to surpass the scrape timeouts, so we should monitor these and set alerts around it.

**Comment by tumido** [comment]
Closed via https://github.com/operate-first/apps/pull/268

**Comment by HumairAK** [comment]
@tumido  -- the pr above was an update to the scrapetimeout value, it didn't actually add monitoring for it as this issue request, my "related" comment should have been more clear, woops.

**Comment by tumido** [comment]
Sorry too quick to close, on my end. I should pay more close attention. :slightly_smiling_face:

**Comment by 4n4nd** [comment]
A little more description:
Recently the cluster metric data being scraped by Prometheus was increased greatly and this resulted in Prometheus taking longer to collect metric data from Openshift cluster monitoring. So we had to increase the metric timeout in PR (https://github.com/operate-first/apps/pull/268).

We need to set up an alert that tells us when the scrape duration for Openshift cluster monitoring is about to reach it's current limit. Since we already have the metrics available, this is a matter of adding an alerting rule just like the Operate First availability rules we have [here](https://github.com/operate-first/apps/blob/master/odh/base/monitoring/overrides/prometheus-operator/overlays/alerts/prometheus-rules.yaml).

**Comment by 4n4nd** [comment]
This issue can now be closed as the alerts for scrape duration were added in https://github.com/operate-first/apps/pull/276
