### ISSUE TITLE
Scraping ArgoCD Metrics from infra cluster

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/SRE#97]
The MOC ArgoCD instance was moved to the infra cluster which resulted in the ArgoCD Prometheus Metrics being unavailable (#83).
The two possible solutions I can think of rn are:
1. Set up a new Prometheus in infra cluster that collects the ArgoCD metrics (and possibly other metrics in the future).
2. Expose all ArgoCD metrics routes and have them scraped by the CNV OperateFirst Monitoring Prometheus.

**Comment by HumairAK** [comment]
For now I like (2) offers the path of least resistance to get our alerts for argocd back.  (1) seems like it requires more discussion, like -- where is prometheus coming from ? odh->prom operator? or prom-operator directly?

**Comment by 4n4nd** [comment]
Yeah we can go with 2.) for now, but we should start a discussion for the infra cluster monitoring

**Comment by HumairAK** [comment]
Agreed, we can have another issue to discuss monitoring in general for infra.

**Comment by tumido** [comment]
Since the infra cluster is fully managed for us, I'd say we should leverage the cluster monitoring in here. There's no workload owned by other teams expected on this cluster, so we can freely use the cluster monitoring to our benefit. WDYT?

**Comment by tumido** [comment]
@4n4nd we can use the cluster monitoring here. The Infra cluster is meant to be a small management hub cluster for managing other OCP clusters. This cluster is under our full control and we don't expect any "private" community team to deploy their workloads in there. We expect to have deployed the minimal amount of applications to it. That means only:

1. ACM
2. ArgoCD
3. SSO
Maybe few others.

Openshift comes with the cluster management set up. Since we own this cluster, we can leverage it and enrich it with alerts for our management apps:

https://docs.openshift.com/container-platform/4.6/monitoring/managing-alerts.html#creating-alerting-rules-for-user-defined-projects_managing-alerts

I don't see a point to deploying Prometheus on this particular cluster multiple times.

**Comment by HumairAK** [comment]
I think I agree with @tumido here, but I think we should move this discussion to a different issue and scope this to just argocd metrics. @4n4nd can you do the 2nd solution and disable the alerts for the old Argocd cluster so we can close these?

- https://github.com/operate-first/SRE/issues/96
- https://github.com/operate-first/SRE/issues/95
- https://github.com/operate-first/SRE/issues/94

**Comment by 4n4nd** [comment]
> but I think we should move this discussion to a different issue

yeah let's do that


> @4n4nd can you do the 2nd solution and disable the alerts for the old Argocd cluster

Yeah sure :+1:

**Comment by 4n4nd** [comment]
Blocker: https://github.com/operate-first/apps/issues/285

**Comment by 4n4nd** [comment]
still blocked

**Comment by 4n4nd** [comment]
Metrics are now available: [link](http://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/new/graph?g0.expr=up%7Bjob%3D%22argocd%22%7D&g0.tab=1&g0.stacked=0&g0.range_input=1h)
